### ISSUE TITLE
 Download through NAT

### ISSUE THREAD

**Issue by GrubSerg** [loathingKernel/ariadne-bootloader#36]
Hello!

There was a problem with the firmware over the network through NAT. The TFTP server generates random ports during data transfer and there is no way to forward them. Is it possible to make a port permanent?

**Comment by loathingKernel** [comment]
It is not random. The write request on the arduino is the default 69 and the data transfer port is 46969. If you need to change those, you will need to flash the network settings to the eeprom, or edit and recompile the bootloader

**Comment by loathingKernel** [comment]
The communication port is the default 69, and the data transfer port is statically set to 46969. If you want to change them, you will have to edit the source and rebuild the boot loader.

**Comment by GrubSerg** [comment]
Thanks for the very prompt reply. Probably the problem is in my port forwarding settings. It doesn’t work out yet. I will think. Did you flash through the router?

**Comment by loathingKernel** [comment]
Yes I have flashed through a router from a client running on an external machine to an Arduino in my LAN.

**Comment by GrubSerg** [comment]
I apologize for the persistence, but could not show an example of port forwarding.

**Comment by loathingKernel** [comment]
Have you read the documentation [here](https://loathingkernel.github.io/ariadne-bootloader/)?
There is a section, that explains the basics of the process. It doesn't go in detail about how to port forward but has a link to an external wiki for that.

**Comment by GrubSerg** [comment]
Thanks for answers. The problem was in the router settings. )))))
